version: '3'

services:
  api:
    build: .
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - PORT=5000
      - DATABASE_URL=mongodb://mongo:27017/gestion-boutique
      - NODE_ENV=production
    volumes:
      - ./src:/app/src

  mongo:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:

  